In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
"""
Purpose: After setting up the cave client
token and access, purpose is to demonstrate
how to use CAVE to interface with microns data
- retrieve mesh
- retrieve, query synapses
- 

CAVE Documentation source:
https://github.com/AllenInstitute/MicronsBinder/blob/master/notebooks/mm3_intro/MeshAccess.ipynb
"""

'\nPurpose: After setting up the cave client\ntoken and access, purpose is to demonstrate\nhow to use CAVE to interface with microns data\n- retrieve mesh\n- retrieve, query synapses\n- \n\nCAVE Documentation source:\nhttps://github.com/AllenInstitute/MicronsBinder/blob/master/notebooks/mm3_intro/MeshAccess.ipynb\n'

In [3]:
# !pip3 install cloud-volume --upgrade
# !pip3 install caveclient --upgrade
# !pip3 install load_dotenv

In [4]:
import cloudvolume
import caveclient

# Setting up the Cave Interface

In [10]:
from neurd.cave_interface import CaveInterface
from pathlib import Path
client = CaveInterface(
    "minnie65_public",
    env_filepath=Path("./.env").absolute()
)
client

In [18]:
seg_id = 864691137197197121
seg_id = 864691137198252609

# Action 1: Downloading the mesh

In [19]:
mesh = client.mesh_from_seg_id(
    seg_id
)

Warning: deduplication not currently supported for this layer's variable layered draco meshes

In [21]:
from mesh_tools import trimesh_utils as tu
dec_mesh = tu.decimate(mesh,decimation_ratio=0.25)
dec_mesh

xvfb-run -n 2057 -s "-screen 0 800x600x24" meshlabserver $@  -i /neurd_packages/NEURD/Applications/Tutorials/VDI_microns/temp/neuron_35288.off -o /neurd_packages/NEURD/Applications/Tutorials/VDI_microns/temp/neuron_35288_decimated.off -s /neurd_packages/NEURD/Applications/Tutorials/VDI_microns/temp/decimation_meshlab_25258933.mls

In [22]:
from datasci_tools import ipyvolume_utils as ipvu
ipvu.plot_objects(dec_mesh)

/usr/local/lib/python3.8/dist-packages/traittypes/traittypes.py:97: UserWarning: Given trait value dtype "float64" does not match required type "float64". A coerced copy has been created.
  warnings.warn(

Container(figure=Figure(box_center=[0.5, 0.5, 0.5], box_size=[1.0, 1.0, 1.0], camera=PerspectiveCamera(fov=45.â€¦

# Action 2: Downloading the synapses

In [23]:
syn_df = client.pre_post_df_from_seg_id(seg_id)
syn_df

,id,created,superceded_id,valid,size,pre_pt_supervoxel_id,pre_pt_root_id,post_pt_supervoxel_id,post_pt_root_id,pre_pt_position,post_pt_position,ctr_pt_position
0,215360645,2020-11-04 06:49:11.546047+00:00,NaN,t,864,93735910231040132,864691137198252609,93735910231031165,864691135902080478,"[210560, 96114, 25345]","[210658, 96130, 25337]","[210610, 96064, 25344]"
1,173939647,2020-11-04 06:58:26.675701+00:00,NaN,t,564,90432015295444176,864691137198252609,90432015295433083,864691135758973006,"[186856, 121812, 25683]","[186808, 121806, 25674]","[186834, 121831, 25677]"
2,203064053,2020-11-04 07:15:04.596481+00:00,NaN,t,13320,92412579468755057,864691137198252609,92412648188223402,864691135319320488,"[201016, 198294, 26786]","[201074, 198398, 26782]","[201056, 198326, 26782]"
3,241323899,2020-11-04 07:20:31.777609+00:00,NaN,t,2332,95985923137186729,864691137198252609,95985923137192923,864691136272989374,"[227240, 82650, 23993]","[227360, 82680, 24002]","[227316, 82612, 23994]"
4,195794757,2020-11-04 07:36:44.085358+00:00,NaN,t,1696,92195425586748585,864691137198252609,92195425586759404,864691133114428938,"[199482, 153106, 24245]","[199402, 153130, 24253]","[199427, 153094, 24252]"
...,...,...,...,...,...,...,...,...,...,...,...,...
4234,205749107,2020-11-04 14:39:16.199859+00:00,NaN,t,1152,92894027921317486,864691135754357197,92894027921323767,864691137198252609,"[204560, 115120, 25143]","[204580, 115142, 25148]","[204586, 115110, 25144]"
4235,198757478,2020-11-04 14:28:33.973388+00:00,NaN,t,2052,92403095577157437,864691136237813820,92473464321348302,864691137198252609,"[201198, 127448, 22341]","[201262, 127486, 22344]","[201266, 127452, 22345]"
4236,194245814,2020-11-04 11:37:44.490436+00:00,NaN,t,4208,92050015174242345,864691136371491976,92050083893703867,864691137198252609,"[198278, 118434, 24474]","[198268, 118542, 24463]","[198304, 118474, 24471]"
4237,198655508,2020-11-04 11:43:28.447843+00:00,NaN,t,5964,92543283578066022,864691135394307317,92543283578057893,864691137198252609,"[202028, 123376, 24296]","[201942, 123338, 24291]","[201964, 123332, 24295]"
4238,191447790,2020-11-04 09:11:21.696326+00:00,NaN,t,2664,92121208417629095,864691135700772731,92121208417636394,864691137198252609,"[198854, 124126, 23187]","[198866, 124192, 23189]","[198848, 124142, 23196]"

,segment_id,segment_id_secondary,synapse_id,prepost,synapse_x,synapse_y,synapse_z,synapse_size
0,864691137198252609,864691135902080478,215360645,pre,210610,96064,25344,864
1,864691137198252609,864691135758973006,173939647,pre,186834,121831,25677,564
2,864691137198252609,864691135319320488,203064053,pre,201056,198326,26782,13320
3,864691137198252609,864691136272989374,241323899,pre,227316,82612,23994,2332
4,864691137198252609,864691133114428938,195794757,pre,199427,153094,24252,1696
...,...,...,...,...,...,...,...,...
4234,864691137198252609,864691135754357197,205749107,post,204586,115110,25144,1152
4235,864691137198252609,864691136237813820,198757478,post,201266,127452,22345,2052
4236,864691137198252609,864691136371491976,194245814,post,198304,118474,24471,4208
4237,864691137198252609,864691135394307317,198655508,post,201964,123332,24295,5964
4238,864691137198252609,864691135700772731,191447790,post,198848,124142,23196,2664

,segment_id,segment_id_secondary,synapse_id,prepost,synapse_x,synapse_y,synapse_z,synapse_size
0,864691137198252609,864691135902080478,215360645,pre,210610,96064,25344,864
1,864691137198252609,864691135758973006,173939647,pre,186834,121831,25677,564
2,864691137198252609,864691135319320488,203064053,pre,201056,198326,26782,13320
3,864691137198252609,864691136272989374,241323899,pre,227316,82612,23994,2332
4,864691137198252609,864691133114428938,195794757,pre,199427,153094,24252,1696
...,...,...,...,...,...,...,...,...
4234,864691137198252609,864691135754357197,205749107,post,204586,115110,25144,1152
4235,864691137198252609,864691136237813820,198757478,post,201266,127452,22345,2052
4236,864691137198252609,864691136371491976,194245814,post,198304,118474,24471,4208
4237,864691137198252609,864691135394307317,198655508,post,201964,123332,24295,5964
4238,864691137198252609,864691135700772731,191447790,post,198848,124142,23196,2664

# Action 3: Get the Nucleus Ids

In [7]:
nucleus_df = client.neuron_nucleus_df()
nucleus_df

Table Owner Notice on nucleus_ref_neuron_svm: Please cite https://doi.org/10.1101/2022.07.20.499976 when using this table.

,id_ref,created_ref,valid_ref,volume,pt_supervoxel_id,pt_root_id,id,created,valid,target_id,classification_system,cell_type,pt_position,bb_start_position,bb_end_position
0,485509,2020-09-28 22:41:05.119717+00:00,t,348.351529,103588564537113366,864691136740606812,4,2023-03-19 17:46:12.522554+00:00,t,485509,is_neuron,neuron,"[282608, 103808, 20318]","[nan, nan, nan]","[nan, nan, nan]"
1,113721,2020-09-28 22:44:25.300848+00:00,t,251.063828,79951332685465031,864691135208436345,6,2023-03-19 17:46:12.523963+00:00,t,113721,is_neuron,neuron,"[110208, 153664, 23546]","[nan, nan, nan]","[nan, nan, nan]"
2,263203,2020-09-28 22:41:02.988866+00:00,t,238.230405,87694643458256575,864691136194511948,7,2023-03-19 17:46:12.524663+00:00,t,263203,is_neuron,neuron,"[166512, 174176, 24523]","[nan, nan, nan]","[nan, nan, nan]"
3,456177,2020-09-28 22:42:07.371870+00:00,t,358.182257,102677963354799688,864691134965388575,8,2023-03-19 17:46:12.525367+00:00,t,456177,is_neuron,neuron,"[275616, 135120, 24873]","[nan, nan, nan]","[nan, nan, nan]"
4,364447,2020-09-28 22:44:38.430335+00:00,t,269.726188,94449079618306553,864691135975515247,9,2023-03-19 17:46:12.526046+00:00,t,364447,is_neuron,neuron,"[216064, 166800, 15025]","[nan, nan, nan]","[nan, nan, nan]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89054,256280,2020-09-28 22:43:53.850893+00:00,t,354.738012,87546415009833381,864691135495249040,144116,2023-03-19 17:53:24.168939+00:00,t,256280,is_neuron,neuron,"[165808, 118256, 20198]","[nan, nan, nan]","[nan, nan, nan]"
89055,258113,2020-09-28 22:43:32.150344+00:00,t,355.082076,88181726572292650,864691135889739145,144117,2023-03-19 17:53:24.169602+00:00,t,258113,is_neuron,neuron,"[170320, 132992, 20225]","[nan, nan, nan]","[nan, nan, nan]"
89056,258355,2020-09-28 22:41:35.026623+00:00,t,177.375805,88042363741612639,864691135937582340,144118,2023-03-19 17:53:24.170333+00:00,t,258355,is_neuron,neuron,"[169456, 143168, 22057]","[nan, nan, nan]","[nan, nan, nan]"
89057,256602,2020-09-28 22:41:40.109977+00:00,t,193.776845,87969795974184791,864691135737905540,144119,2023-03-19 17:53:24.171316+00:00,t,256602,is_neuron,neuron,"[168512, 126896, 22073]","[nan, nan, nan]","[nan, nan, nan]"
89058,260817,2020-09-28 22:43:58.227026+00:00,t,195.363963,88607100468587301,864691135776412845,144120,2023-03-19 17:53:24.172112+00:00,t,260817,is_neuron,neuron,"[173104, 156464, 22608]","[nan, nan, nan]","[nan, nan, nan]"

In [11]:
nucleus_seg_ids = client.segment_ids_with_nucleus()
nucleus_seg_ids.shape

Table Owner Notice on nucleus_ref_neuron_svm: Please cite https://doi.org/10.1101/2022.07.20.499976 when using this table.

array([                 0, 864691131906133483, 864691132144578807, ...,
       864691137198243393, 864691137198252609, 864691137198255681])